# Generated by Django 3.1.6 on 2021-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSales', '0002_auto_20210213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
