# Generated by Django 3.1.6 on 2021-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSales', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
